### ISSUE TITLE
flutter使用 音视频不同步，狂刷日志W/GLConsumer: [SurfaceTexture-0-711-2] bindTextureImage: clearing GL error: 0x500

### ISSUE THREAD

**Issue by luying6** [tencentyun/SuperPlayer_Android#100]
flutter使用，但是出现了画面延时并且logcat 一直刷
W/GLConsumer: [SurfaceTexture-0-711-2] bindTextureImage: clearing GL error: 0x500
这个错误

**Comment by whalehe** [comment]
您好，这个是系统warning日志，可以忽略。可以更新下我们最新版本7.4，如果还有问题，烦请附上日志或者截图信息。还有机型相关信息
