### ISSUE TITLE
你们上传视频的DEMO问题多多,

### ISSUE THREAD

**Issue by PrinceIce10** [tencentyun/SuperPlayer_Android#103]
既然要封装,就封装完全点, 给个SDK用就好了, 封装又没封装好, 还搞出那么多类互相耦合, 真是服了, 最简单粗暴的方式,
1, 要么封装好,给出完整的引用实例;
2, 要么直接给出最简单的操作步骤,我们自己封装. 
现在的结果是: 封装不完全, 我们还得一步步理清笔者的思路, 然后才能引进自己的项目, 超级蛋疼的好不. 墙都不扶就服笔者.

**Comment by whalehe** [comment]
您好，可以更新下我们最新版本7.4，如果还有问题，烦请附上日志或者截图信息。
