### ISSUE TITLE
代码没法运行

### ISSUE THREAD

**Issue by yyclang** [tencentyun/SuperPlayer_Android#105]
用studio 里git工具下载下来，代码没法运行起来，环境如何构建，希望指点一下

**Comment by whalehe** [comment]
1、git clone https://github.com/tencentyun/SuperPlayer_Android.git

2、Android Studio 3.5+版本以上，open project就可以了，

如果有错误，烦请贴下截图或者日志

**Comment by yyclang** [comment]
[](url)

> 1、git clone https://github.com/tencentyun/SuperPlayer_Android.git
> 
> 2、Android Studio 3.5+版本以上，open project就可以了，
> 
> 如果有错误，烦请贴下截图或者日志

![1594262486798](https://user-images.githubusercontent.com/8086629/86991146-e7878c80-c1d0-11ea-9ac4-a67e5489f21e.jpg)

**Comment by yyclang** [comment]
构建的环境也不报什么错误，就是点击build里make，会出现这个上面的弹框，点ok也看不出什么错误

**Comment by yyclang** [comment]
我的ide版本是3.6

**Comment by yyclang** [comment]
奇了怪，先前下你们的7.2.8927版本编译环境没有一点问题，下你们最新版本玩不转了
