### ISSUE TITLE
一个播放器sdk 40M 你们是认真的吗？

### ISSUE THREAD

**Issue by YuJunKui1995** [tencentyun/SuperPlayer_Android#11]

**Comment by AlphaHans** [comment]
您好，aar 包含调试符信息，在release包下编译器会自动去掉相关调试符，可以打包对比实际增量的大小。

**Comment by YuJunKui1995** [comment]
可是我看了。编译后的光so就有15M+ 单平台

**Comment by AlphaHans** [comment]
player 版本定位需要兼容所有格式的视频，打包了额外的so库，增量符合预期。

**Comment by fanturbo** [comment]
hi，问下如何尽量缩小sdk的大小呢，比如说我只想支持MP4和flv格式的视频

**Comment by AlphaHans** [comment]
@fantouch  体积已经无法再缩小。建议做单架构集成，如果 15M 依旧过大，建议进行 so 的动态下发。

**Comment by fanturbo** [comment]
@AlphaHans 好的，thanks.15M在可接受范围内

**Comment by AlphaHans** [comment]
@YuJunKui1995 @fanturbo  这边单架构 SO 不应该有 15 M这么多。 
详情见 ：https://github.com/tencentyun/SuperPlayer_Android/issues/26
