### ISSUE TITLE
与TUIKit库冲突，怎么解决，使用专业版的也不行

### ISSUE THREAD

**Issue by zzzsssbo** [tencentyun/SuperPlayer_Android#113]

**Comment by 284419487** [comment]
新版 IM tuikit 中包含了 TRTC 依赖，如果要和播放器 sdk一起使用，需要将依赖替换成专业版。参考文档：https://cloud.tencent.com/document/product/454/7873
![image](https://user-images.githubusercontent.com/48011978/97838526-5312de00-1d1b-11eb-8546-15bfd149d464.png)
