### ISSUE TITLE
进度条有没有seekTo功能

### ISSUE THREAD

**Issue by StarAndRainbow** [tencentyun/SuperPlayer_Android#125]
当用户看视频看到一半的时候，退出了，下次用户进来想接着上一次的进度播放。有没有方法可以在固定的进度上面开始播放呢。而不是重头开始放呢？我找不到类似的方法

**Comment by StarAndRainbow** [comment]
Android】-【代码移动进度条功能有没有？？?】
【集成包】：LiteAVSDK_Player_7.5.9307.aar
【当前现象】：Android Studio集成新版本SDK。当用户看视频看到一半的时候，退出了，下次用户进来想接着上一次的进度播放。有没有方法可以在固定的进度上面开始播放呢。而不是重头开始放呢？我找不到类似的方法
【机型】：如华为Mate 20
【有无日志或者截图】：暂无日志

**Comment by StarAndRainbow** [comment]
Android】-【代码移动进度条功能有没有？？?】
【集成包】：LiteAVSDK_Player_7.5.9307.aar
【当前现象】：Android Studio集成新版本SDK。当用户看视频看到一半的时候，退出了，下次用户进来想接着上一次的进度播放。有没有方法可以在固定的进度上面开始播放呢。而不是重头开始放呢？我找不到类似的方法
【机型】：小米8，小米10，华为mate30等等等
【有无日志或者截图】：暂无日志

**Comment by zzzsssbo** [comment]
sdk自带的有的

**Comment by StarAndRainbow** [comment]
> sdk自带的有的

兄弟，可以说说是那个方法吗，实在找不到这个方法在那个类里面，官网也没找到这个方法

**Comment by zzzsssbo** [comment]
看你说的场景，你用的应该是点播播放器，那么可以在开始播放前调用setStartTime（）方法，从指定时间开始播放。

**Comment by StarAndRainbow** [comment]
> 看你说的场景，你用的应该是点播播放器，那么可以在开始播放前调用setStartTime（）方法，从指定时间开始播放。
找到你说的这个方法了，谢谢
