### ISSUE TITLE
关于java.lang.UnsatisfiedLinkError，有个问题想了解一下

### ISSUE THREAD

**Issue by Vander-liu** [tencentyun/SuperPlayer_Android#139]
最近项目准备使用腾讯云推流 + 客户端使用播放器SDK aar做直播播流

在Android Studio这两天本地调试过程中，几乎每天一次会出现java.lang.UnsatisfiedLinkError这个错误

日志如下：

![image](https://user-images.githubusercontent.com/16666953/109384005-1b145400-7925-11eb-806d-f436a25dde83.png)

开始我以为我配置有问题，然后对着Demo工程，将各类配置全部添加

配置如下：
```
    packagingOptions {
        //腾讯云播放器SDK配置开始
        pickFirst '**/libc++_shared.so'
        doNotStrip "*/armeabi/libYTCommon.so"
        doNotStrip "*/armeabi-v7a/libYTCommon.so"
        doNotStrip "*/x86/libYTCommon.so"
        doNotStrip "*/arm64-v8a/libYTCommon.so"
        //腾讯云播放器SDK配置结束
    }

```
    repositories {
        flatDir {
            dirs 'libs'
            dirs project(':app').file('libs')
        }
}
```
```
        ndk {
            abiFilters "armeabi-v7a"
        }
```
之后在调试过程中，还是出现java.lang.UnsatisfiedLinkError

出现问题时，将运行的APK逆向看了一下，发现播放器需要的so全部都在

```
![image](https://user-images.githubusercontent.com/16666953/109384109-9970f600-7925-11eb-9f6b-de6357f2d6ac.png)

```

**Comment by Vander-liu** [comment]
使用机型 XiaoMi Lite 8  Android 8.1

**Comment by Vander-liu** [comment]
开启播放器SDK的日志，收集到的数据如下：

[[超长消息]2021-02-25 .pdf](https://github.com/tencentyun/SuperPlayer_Android/files/6054139/2021-02-25.pdf)

**Comment by Vander-liu** [comment]
问题1：因为目前处于Android Studio Debug调试阶段，不太清楚播放器SDK线上，是否也会有此类异常
问题2：该异常的产生，会不会可能由于Android Stuido Debug运行产生，而线上环境用户自行安装APK不会存在该问题。
问题3：根据该异常，查询相关问题，以及同事推荐，发现Relinker相关库，不知道该问题是否和这个方案遇到的场景类似

参考：
https://www.csdn.net/article/2015-11-10/2826182-the-perils-of-loading-native-libraries-on-android
https://github.com/KeepSafe/ReLinker

**Comment by Vander-liu** [comment]
@whalehe

**Comment by Vander-liu** [comment]
相关问题：
https://github.com/tencentyun/SuperPlayer_Android/issues/129
https://github.com/tencentyun/SuperPlayer_Android/issues/108
https://github.com/tencentyun/SuperPlayer_Android/issues/65

**Comment by Vander-liu** [comment]
希望官方大大能够指导一下

**Comment by Vander-liu** [comment]
Relinker 解决UnsatisfiedLinkError 产生场景

/**
* Try to load a native library using a workaround of
* http://b/13216167.
*
* Workaround for b/13216167 was adapted from code in
* https://googleplex-android-review.git.corp.google.com/#/c/433061
*
* More details about http://b/13216167:
* PackageManager may fail to update shared library.
*
* Native library directory in an updated package is a symbolic link
* to a directory in /data/app-lib/<package name>, for example:
* /data/data/com.android.chrome/lib -> /data/app-lib/com.android.chrome[-1].
* When updating the application, the PackageManager create a new directory,
* e.g., /data/app-lib/com.android.chrome-2, and remove the old symlink and
* recreate one to the new directory. However, on some devices (e.g. Sony Xperia),
* the symlink was updated, but fails to extract new native libraries from
* the new apk.
+
* We make the following changes to alleviate the issue:
* 1) name the native library with apk version code, e.g.,
* libchrome.1750.136.so, 1750.136 is Chrome version number;
* 2) first try to load the library using System.loadLibrary,
* if that failed due to the library file was not found,
* search the named library in a /data/data/com.android.chrome/app_lib
* directory. Because of change 1), each version has a different native
* library name, so avoid mistakenly using the old native library.
*
* If named library is not in /data/data/com.android.chrome/app_lib directory,
* extract native libraries from apk and cache in the directory.
*
* This function doesn’t throw UnsatisfiedLinkError, the caller needs to
* check the return value.
*/

**Comment by Vander-liu** [comment]
@Tencent-Alice

**Comment by AndroidSWJ** [comment]
你好，请问这个问题你解决了吗？查一下下面的问题：
1. 出现问题的时候，apk的安装目录，可以用adb shell pm path com.xxxx(包名)得到base.apk路径，cd到上层目录，进入lib，比如：/data/app/com.qiwu.gysh-o1MnVsigxVUTvYZGWmURtw==/lib/arm下是否有相应的so？
2. 出现问题的apk能够原样保留发给我们定位下呢？可以用adb pull 上面的base.apk

**Comment by Vander-liu** [comment]
@AndroidSWJ  1.之前本地运行的时候，这个问题是一直存在的。
2.查看打好包的APK，So也是存在的。
3.本地调试的时候高版本的Android设备不存在该问题，例如Android10+，另一台Android8.0还会一直出现。

**Comment by Vander-liu** [comment]
这个问题别花时间了，毕竟离我提问过去时间太久了。就是咱们的效率有点。。。。
