### ISSUE TITLE
是否支持后台播放

### ISSUE THREAD

**Issue by LayneCui** [tencentyun/SuperPlayer_Android#140]
我想问一下，应用后台播放时，sdk 有做相关保活工作吗？还是需要自己处理？

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，您在播放的时候切换都后台，这边是有保活的，您这边也可以使用这边的demo测试一下
https://cloud.tencent.com/document/product/881/20204
技术问题 欢迎交流 q2562367495 注明来意
