### ISSUE TITLE
从指定时间点进行播放

### ISSUE THREAD

**Issue by AnYuer** [tencentyun/SuperPlayer_Android#15]
大神，怎么从指定时间点进行播放？跪求超级播放器的api文档，我找遍了腾讯云都找不到 。跪求，谢谢

**Comment by AlphaHans** [comment]
超级播放器高度封装了 对外没有提供seek，你可以查看SuperPlayerView.java文件，搜索seek方法 直接使用SDK的seek方法，自己封装对外即可。

**Comment by AnYuer** [comment]
大神，我设置了seek方法，但是没起作用了，心塞啊，您那边有小demo吗？从指定时间点进度  开始播放。

**Comment by AlphaHans** [comment]
建议在onPlayEvent中收到首帧开始播放的时候再seek。 视频未真正开始播放前设置是无效的。

**Comment by AnYuer** [comment]
解决了，谢谢大神，谢谢你
