### ISSUE TITLE
安卓11 配置arm64-v8a架构 并 targetSdkVersion=30 m3u8无法播放

### ISSUE THREAD

**Issue by wushangjun** [tencentyun/SuperPlayer_Android#153]
【Android】-【8.7.10102】：【安卓11 配置arm64-v8a架构 并 targetSdkVersion=30 m3u8无法播放】
【集成包】：LiteAVSDK_Player_Android_8.7.10102
【当前现象】：SuperPlayer_Android 提供的demo，使用安卓11手机。 配置arm64-v8a架构 并 targetSdkVersion=30，m3u8格式无法播放。测试MP4格式能正常播放。
【机型】：小米11
【之前版本有无此问题】：第一次使用
【有无日志或者截图】：
![image](https://user-images.githubusercontent.com/17995901/119594665-ccd0fd00-be0e-11eb-8c71-37ce864d57f9.png)

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，可以参看#150看下
如果还未解决，欢迎交流 q2562367495 注明来意

**Comment by wushangjun** [comment]
请用官方SuperPlayer_Android demo ，更换成以上配置，可以复现这个问题

**Comment by YangHang801** [comment]
一样，也是小米11我™调了一上午才发现targetSdkVersion = 30问题
我还奇了怪了官方demo设置arm64-v8a没问题，demo的targetSdkVersion是26

**Comment by wushangjun** [comment]
> 一样，也是小米11我™调了一上午才发现targetSdkVersion = 30问题
> 我还奇了怪了官方demo设置arm64-v8a没问题，demo的targetSdkVersion是26

提交工单了。那边回复说会处理一下，只能等等了

**Comment by ZevShiShi** [comment]
这个问题其实就是他们的缓存对m3u8的支持有问题，现在先去掉缓存就好了，可以试试
···java···
    private void setPlayerConfig(TXVodPlayer player) {
        TXVodPlayConfig mConfig = new TXVodPlayConfig();
        mConfig.setCacheFolderPath(getFilesDir().getAbsolutePath() + "/txcache");
        //指定本地最多缓存多少文件，避免缓存太多数据
        mConfig.setMaxCacheItems(10);
//        player.setConfig(mConfig);
    }

**Comment by wushangjun** [comment]
新版本已没发现此问题
