### ISSUE TITLE
SuperPlayerView 需要增加循环方法 setLoop

### ISSUE THREAD

**Issue by lijy91** [tencentyun/SuperPlayer_Android#154]
目前 iOS 版本有该功能，但 Android 版本没有。

```objc
[_superPlayerView setLoop:YES];
```

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，可以参照点播播放器
1.点播是有提供该接口的mVodPlayer.setLoop(true);
https://liteav.sdk.qcloud.com/doc/api/zh-cn/group__TXVodPlayer__android.html#a3f5ae863c82509d1ed266503e8138781 
2、IOS实现
/// 循环播放
@property (nonatomic) BOOL loop;
[self.vodPlayer setLoop:self.loop];
3、建议在SuperPlayer中先自行封装下。
![A9BACD17-8810-4FD3-8FE7-94E16968D202](https://user-images.githubusercontent.com/74762384/120739979-e7008e80-c524-11eb-8b51-bf065c293907.png)
后续会补上，如还有技术问题 ，欢迎交流 q2562367495 注明来意
