### ISSUE TITLE
拖动快进会重置缓存的数据，导致重新加载

### ISSUE THREAD

**Issue by LiuDeng** [tencentyun/SuperPlayer_Android#155]
拖动快进会重置缓存的数据，导致重新加载。之前缓存的数据就白缓存了。

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，可以拍个视频复现下，便于进一步定位问题
技术问题 欢迎交流 q2562367495 注明来意

**Comment by LiuDeng** [comment]
@Tencent-Alice 您好，我们录了一个视频哈：https://www.bilibili.com/video/BV1jM4y1g7ye/  您可以看下视频内容，底部进度条显示后面的内容已经缓存了，并且此时网速也为0了，表示不从网络加载了，在这种情况下我们拖动进度到后面导致所有缓存全部被清空，又需要重新加载了，网络速度也有了。
目前我们使用的是TXVodPlayer组件。SuperPlayer_Android版本是Version 8.8 @ 2021.06.17， 此问题之前几个版本也存在哈。
这个问题是我们被用户吐槽最多的点，恳请修复。
谢谢~祝好~

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，和您确认下，您这边指的缓存到本地后，还是默认播放时缓存到内存之后加载，方便进一步定位问题
技术问题 欢迎交流 q2562367495 注明来意

**Comment by LiuDeng** [comment]
是默认播放时缓存到内存的那部分，没有缓存到本地

**Comment by LiuDeng** [comment]
我们尝试了用exoplayer就没有这个问题，同样是内存中的。

**Comment by LiuDeng** [comment]
@Tencent-Alice 有问题可以再问我哈，在线求修复~祝好~
