### ISSUE TITLE
拖动快进会重置缓存的数据，导致重新加载

### ISSUE THREAD

**Issue by LiuDeng** [tencentyun/SuperPlayer_Android#160]
您好，我们录了一个视频哈：https://www.bilibili.com/video/BV1jM4y1g7ye/ 您可以看下视频内容，底部进度条显示后面的内容已经缓存了，并且此时网速也为0了，表示不从网络加载了，在这种情况下我们拖动进度到后面导致所有缓存全部被清空，又需要重新加载了，网络速度也有了。
是默认播放时缓存到内存的那部分，没有缓存到本地。我们尝试了用exoplayer就没有这个问题，同样是内存中的。
目前我们使用的是TXVodPlayer组件。SuperPlayer_Android版本是Version 8.8 @ 2021.06.17， 此问题之前几个版本也存在哈。
这个问题是我们被用户吐槽最多的点，恳请修复!~
谢谢~
祝好~

**Comment by Tencent-Alice** [comment]
您好 根据您的问题 在Q上和你有对接，您可以检查一下播放器，是否使用了本地缓存，如果使用了可以把代码去掉，再测试一下![image](https://user-images.githubusercontent.com/74762384/124531687-9e006a80-de41-11eb-959c-91cbf8c3c6c7.png)
参考https://cloud.tencent.com/document/product/881/20216
如还有技术问题 欢迎交流 Q2562367495 注明来意

**Comment by LiuDeng** [comment]
@Tencent-Alice 我们确认没有使用本地缓存。
![屏幕快照 2021-07-07 上午11 31 29](https://user-images.githubusercontent.com/1720312/124696042-e9387d00-df16-11eb-8a86-95de1d0c176d.png)

**Comment by zijin2014** [comment]
> 您好 根据您的问题 在Q上和你有对接，您可以检查一下播放器，是否使用了本地缓存，如果使用了可以把代码去掉，再测试一下![image](https://user-images.githubusercontent.com/74762384/124531687-9e006a80-de41-11eb-959c-91cbf8c3c6c7.png)
> 参考https://cloud.tencent.com/document/product/881/20216
> 如还有技术问题 欢迎交流 Q2562367495 注明来意

确实存在这个问题，seek后会重新加载已经缓冲过的数据，使用的是最新版本sdk
