### ISSUE TITLE
SuperPlayerView播放视频，不会进入缓冲回调，请问这是什么原因呢

### ISSUE THREAD

**Issue by zijin2014** [tencentyun/SuperPlayer_Android#168]
播放地址http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，请提供下监听代码截图，方便确认问题
技术问题 欢迎交流 q2562367495 注明来意

**Comment by zijin2014** [comment]
> 您好，根据您的问题，请提供下监听代码截图，方便确认问题
> 技术问题 欢迎交流 q2562367495 注明来意

这个问题我解了，请问如何获取缓冲进度呢？给seekbar设置第二进度
