### ISSUE TITLE
拖动进度小圆点的时候, 小圆点一直再鬼畜😂

### ISSUE THREAD

**Issue by HancockY** [tencentyun/SuperPlayer_Android#22]
就是左右不停的抖动

**Comment by AlphaHans** [comment]
seek 和 progress 冲突。 seek的时候，请别允许播放器进度设置setProgress

**Comment by HancockY** [comment]
在TCPointSeekBar中的这段代码: 
private void addThumbAndPointViews() {
        this.post(new Runnable() {
            @Override
            public void run() {
                if (mIsChangePointViews) {
                    TCPointSeekBar.this.removeAllViews();
                    if (mPointList != null) {
                        for (int i = 0; i < mPointList.size(); i++) {
                            PointParams params = mPointList.get(i);
                            addPoint(params, i);
                        }
                    }
                    addThumbView();
                    mIsChangePointViews = false;
                }
                calProgressDis();
//在UI重绘的时候加入这个判断: 拖动时不重绘进度小圆点, 就可以解决这个问题
                if (!mIsOnDrag){
                    changeThumbPos();
                }
            }
        });
    }
