### ISSUE TITLE
播放过程中向左拖动进度条到00:00再往左点的位置, 经常会出现进度条跳到之前正在播放位置, 然后才回到00:00位置, 弄了好久了, 我没能解决...

### ISSUE THREAD

**Issue by HancockY** [tencentyun/SuperPlayer_Android#23]
播放过程中向左拖动进度条到00:00再往左点的位置, 经常会出现进度条跳到之前正在播放位置, 然后才回到00:00位置, 弄了好久了, 我没能解决...

**Comment by HancockY** [comment]
打印了log找到问题, TCPointSeekBar 中的 mThumbLeft 变量在 onDraw() 方法绘制的时候在滑动到00:00位置之后本来应该是变成0, 但是变成0之后mThumbLeft 突然变成了当前播放位置的数, 然后又重新变回0. 感觉是计算位置的时候逻辑有问题, 但是我不会改

**Comment by HancockY** [comment]
问题应该是 SuperPlayerView中, 进度监听onPlayEvent(), 调用了TCVodControllerBase 的 updateVideoProgress(), 而updateVideoProgress()中调用了mSeekBarProgress的setProgress(),
这样即使进度拖拽到0之后, 还是会走一小会setProgress(), 从而使mThumbLeft被mCurrentProgress 赋值为视频当前实际播放进度的距离:
float dis = (mSeekBarRight - mSeekBarLeft) * (mCurrentProgress * 1.0f / mMaxProgress);
mThumbLeft = dis;
这样就又绘制了一会在mCurrentProgress 位置, 出现我描述的问题.

就是说seekbar实际是受手指位置和视频进度2个变量控制的, 手指到0, 但是视频进度还是之前的, 
就跳了回去, 然后视频进度到0, 又重新开始正常移动了.
有点乱, 我不知道改怎么改了

**Comment by HancockY** [comment]
之前想的是错的, 丢人删掉了

**Comment by HancockY** [comment]
这个问题很奇怪, 如果seek之前判断一下, 如果位置是seek到的位置是0的话, 手动改成1, 就没问题了. (只要不是seek到0 都可以.)
TCVodControllerBase中: 
case SuperPlayerConst.PLAYTYPE_VOD:
                if (curProgress >= 0 && curProgress <= maxProgress) {
                    // 关闭重播按钮
                    updateReplay(false);
                    float percentage = ((float) curProgress) / maxProgress;
                    int position = (int) (mVodController.getDuration() * percentage);
                    if (position == 0)
                        position = 1;
                    mVodController.seekTo(position);
                    mVodController.resume();
                }
                break;

**Comment by AlphaHans** [comment]
你好，目前暂未能理解你的意思😢 能把现象描述一下么

**Comment by HancockY** [comment]
@AlphaHans 
好的. 就是播放过程中(比如当前播放到第30秒处), 如果把进度条拖回到00:00位置, 进度条经常会跳转到30秒处一次, 然后再跳到开始位置(00:00处)正常播放.
只有拖拽到开始位置才会出现这种进度条回跳的情况. 拖动到其他位置都不会出现问题.

**Comment by AlphaHans** [comment]
这里后续抽空看下，目前业务繁忙，播放器相关需求需要往后排一下。

**Comment by whalehe** [comment]
您好，建议升级下7.2版本，看看有无问题
