### ISSUE TITLE
不同平台打包时so文件大小差异过大

### ISSUE THREAD

**Issue by goweii** [tencentyun/SuperPlayer_Android#26]
用android studio在Mac和Win上打包后，so文件大小差异过大，如图，请问时什么原因？
![image](https://user-images.githubusercontent.com/5456892/63562682-17b24680-c591-11e9-9cac-975a71ffcf1b.png)

**Comment by AlphaHans** [comment]
打出releaee包比较。 debug包可能平台不同，可能会导致so调试符没有清除。

**Comment by goweii** [comment]
是release包，两个平台都是release包

**Comment by AlphaHans** [comment]
![image](https://user-images.githubusercontent.com/16743494/63588585-74395400-c5d9-11e9-9788-788c6f0d59bb.png)
iMac 单架构 SO 编译出来如图。  

你可能工程依赖有问题，可以使用demo打包试一下。

**Comment by AlphaHans** [comment]
这里对比了一下，你的大小和 aar 中，没有去掉调试符大小的 so 库基本一致。 应该是 AS 没有自动去掉aar中的so调试符信息，请 google 看下如何解决此问题。

**Comment by goweii** [comment]
好的，谢谢
