### ISSUE TITLE
是否跟移动小直播SDK冲突？

### ISSUE THREAD

**Issue by ChenSiWu** [tencentyun/SuperPlayer_Android#27]
app中使用了小直播功能，现在有个需求是要播放其他视频，打算用superPlayer,问下是否跟小直播SDK冲突？如果冲突，我直接使用小直播里面的TXCloudVideoView 会不会造成收费？

**Comment by AlphaHans** [comment]
你好要看你使用的是什么版本。 小直播一般使用专业版或者Smart版，当前github仓库是player版本。 版本覆盖专业版 > Player > Smart ，如果您需要播放器也需要直播功能，请使用专业版。 SDK 本身不会产生收费，你可以使用该View，但涉及到具体功能的时候需要申请License，如直播 短视频等功能，点播播放器目前不需要申请。

**Comment by ChenSiWu** [comment]
@AlphaHans  谢谢，目前项目使用的专业版，直播跟点播都能用。嘿嘿
