### ISSUE TITLE
直播播放的时候，播放时间问题

### ISSUE THREAD

**Issue by superxsx** [tencentyun/SuperPlayer_Android#29]
1、直播播放的时候视频都可以显示，进行播放监听的时候，无法返回状态
event == TXLiveConstants.PLAY_EVT_PLAY_PROGRESS 导致无法更新播放时间，其他状态可以返回，这个怎么回事？

2、Demo中的直播的时候有个小问题，但你播放的时候，然后暂停在播放，发现播放时间无法更新
![IMG_20190917_155335](https://user-images.githubusercontent.com/32897328/65022557-c7e25780-d963-11e9-8c37-dab398c05d2e.jpg)

**Comment by shengcui2018** [comment]
多谢反馈，请提供下版本号。

**Comment by superxsx** [comment]
LiteAVSDK_Professional_6.6.7458

**Comment by dengqicheng** [comment]
LiteAVSDK_Professional_6.7.7734 demo测试也这边应该是点击回复播放事件 进度条ui没有刷新

**Comment by AlphaHans** [comment]
您好，我们将尽快修复此问题

**Comment by whalehe** [comment]
您好，可以更新下我们最新版本7.4，如果还有问题，烦请附上日志或者截图信息。
