### ISSUE TITLE
设置倍速播放

### ISSUE THREAD

**Issue by flowvwrvvsv** [tencentyun/SuperPlayer_Android#3]
设置倍速播放2.0f，播放速度会变慢
![image](https://user-images.githubusercontent.com/16237147/57176465-13033e80-6e8b-11e9-8cdd-09261d6f2bf1.png)

**Comment by AlphaHans** [comment]
实际上视频播放也是有异常么？

**Comment by flowvwrvvsv** [comment]
实际上是没什么异常，但是设置速度时会出现这种效果，比如我正在播放，速度是1.0f，设置播放速度为2.0f，也设置成功了，但是不到一会时间（最多30秒），播放速度会降低，速度从2.0f->1.75->1.5->1.25->1.125，速度慢慢降低，并且logcat上会有上面图片的打印记录，

**Comment by echoYZ1208** [comment]
@flowvwrvvsv 所有视频都有此现象吗？能否提供下视频或者重现方法？

**Comment by flowvwrvvsv** [comment]
时间有点久了，记不住了，出现条件是播放网络视频的时候，然后设置倍速播放以后出现这种情况，我试了几部手机，华为麦芒4，vivo都会出现这种情况，并且logcat上会有我箭头指出的打印记录
