### ISSUE TITLE
SuperPlayerView 体验问题

### ISSUE THREAD

**Issue by turnmind** [tencentyun/SuperPlayer_Android#38]
SuperPlayerView 滑动修改音量太灵敏，包括亮度，进度一下增加太快，一不小心就是声音大的受不了

**Comment by AlphaHans** [comment]
您好，我们将尽快修复此问题。

**Comment by turnmind** [comment]
> 您好，我们将尽快修复此问题。

nice

**Comment by HancockY** [comment]
还有, 每次进入播放界面屏幕亮度会最大化, 系统调节亮度就无效了, 只能调成播放器亮度来调暗

**Comment by wzyzb** [comment]
收到，我们尽快确认你的问题并修复

**Comment by wzyzb** [comment]
android调节亮度可以调节系统亮度和当前activity的亮度，在播放器中是调节的当前activity的亮度。可以修改启动时默认的亮度 在TCVodMoreView 的updateCurrentVolume函数中。

**Comment by HancockY** [comment]
注释掉 设置亮度100%的代码, 解决了, 谢谢~
