### ISSUE TITLE
视频播放回调

### ISSUE THREAD

**Issue by piratejason** [tencentyun/SuperPlayer_Android#40]
现象:视频处于播放状态,网络原因卡住,给了回调状态buffer,同时播放器播放状态为isplaying;
网络正常同时给了buffer状态,播放器播放状态为isplaying;
期望:上述两种状态希望给一个区别的回调

**Comment by echoYZ1208** [comment]
您好，播放器的监听提供有两个接口： onPlayEvent（事件通知） 和 onNetStatus（状态反馈），通过监听onNetStatus可以获取buffer状态但区分不了是否在loading，但可以通过onPlayEvent监听到PLAY_EVT_PLAY_LOADING事件获取播放状态。

**Comment by echoYZ1208** [comment]
详见文档：https://cloud.tencent.com/document/product/881/20216#.E4.BA.8B.E4.BB.B6.E7.9B.91.E5.90.AC
