### ISSUE TITLE
TXLivePlayer播放直播画面黑屏，log提示：invalid frame buffer id

### ISSUE THREAD

**Issue by czeall** [tencentyun/SuperPlayer_Android#41]
使用TXLivePlayer播放rtmp直播时，给TXLivePlayer设置画面渲染的textureView,声音正常但是画面黑屏；log打印：invalid frame buffer id

以下为设置代码：

`  TextureView textureView = findViewById(R.id.texture);
        textureView.setSurfaceTextureListener(new TextureView.SurfaceTextureListener() {
            @Override
            public void onSurfaceTextureAvailable(SurfaceTexture surface, int width, int height) {
                TXLivePlayer txLivePlayer = new TXLivePlayer(MainActivity.this);
                txLivePlayer.setRenderMode(TXLiveConstants.RENDER_MODE_ADJUST_RESOLUTION);
                txLivePlayer.setPlayListener(MainActivity.this);
                txLivePlayer.setSurface(new Surface(surface));
                txLivePlayer.startPlay(rtmpUrl, TXLivePlayer.PLAY_TYPE_LIVE_RTMP);
            }

            @Override
            public void onSurfaceTextureSizeChanged(SurfaceTexture surface, int width, int height) {
            }

            @Override
            public boolean onSurfaceTextureDestroyed(SurfaceTexture surface) {
                return false;
            }

            @Override
            public void onSurfaceTextureUpdated(SurfaceTexture surface) {

            }
        });`

**Comment by czeall** [comment]
如果设置播放资源的type类型为TXLivePlayer.PLAY_TYPE_VOD_HLS，则正常播放画面正常渲染；设置为rtmp资源对应的TXLivePlayer.PLAY_TYPE_LIVE_RTMP则黑屏播放

**Comment by czeall** [comment]
改用surfaceView 进行渲染画面还是有相同问题。

**Comment by czeall** [comment]
@AlphaHans  没人处理吗。

**Comment by AlphaHans** [comment]
您好，这里是为什么需要用SurfaceView或者TextureView渲染。目前Surfce渲染仅提供部分客户使用。 一般客户请使用TXCloudView渲染

**Comment by czeall** [comment]
> 您好，这里是为什么需要用SurfaceView或者TextureView渲染。目前Surfce渲染仅提供部分客户使用。 一般客户请使用TXCloudView渲染


想要完成自定义播放器的某些功能，比如textureView的纹理加工等。其他三方播放器内核都支持了设置surface的功能。可以设置surface的话自定义化会更好。

**Comment by AlphaHans** [comment]
好的，我目前正在开会。麻烦您再稍等一下，大概9.30给您看下这个问题。 您可以先加我的工作微信 hanszhli，稍后跟您这边联系

**Comment by AlphaHans** [comment]
代码缺少调用 
```
setSurfaceSize(w,h)
```

close。
