### ISSUE TITLE
点击视频标题小窗口的返回箭头出行悬浮窗关掉后原本界面只播放音频

### ISSUE THREAD

**Issue by code1136** [tencentyun/SuperPlayer_Android#42]

**Comment by echoYZ1208** [comment]
您好，“悬浮窗关掉后原本界面只播放音频”具体是指点击悬浮窗返回窗口播放模式后没画面有声音吗？能否提供下机型？复现几率如何？

**Comment by code1136** [comment]
就是关闭了悬浮窗播放模式退回原本窗口只能播放声音，可能是SurfaceView没加载到画面了。重复率100%，机型是荣耀v10，用模拟器开发也有。

**Comment by wzyzb** [comment]
好的 我们尽快看一下

**Comment by whalehe** [comment]
你好，建议升级到最新版本7.2，试试看，有无问题
