### ISSUE TITLE
怎么监听播放事件

### ISSUE THREAD

**Issue by zqq5054** [tencentyun/SuperPlayer_Android#44]
如题，比如怎么监听视频播放结束，视频播放进度，文档里啥没有啊？

**Comment by AlphaHans** [comment]
您好，目前超级播放器隐藏了播放细节，播放控制由超级播放器自己完成。具体的处理可以在，`
`
SuperPlayerView 类中：
// 点播回调处理
public void onPlayEvent(TXVodPlayer player, int event, Bundle param) 
// 直播回调处理
public void onPlayEvent(int event, Bundle param)
`
若您想自行进行定制开发，可以参考下篇文档，直接使用 SDK 提供的播放器进行定制开发
https://cloud.tencent.com/document/product/881/20216#.E4.BA.8B.E4.BB.B6.E7.9B.91.E5.90.AC
