### ISSUE TITLE
测试中有个一个视频播放到2:51:39的位置会卡住，日志显示如下，使用了其他播放器不会出现这个问题

### ISSUE THREAD

**Issue by zhangshaobo87** [tencentyun/SuperPlayer_Android#49]
IJKMEDIA: feed_input_buffer, FFP_MSG_VIDEO_DECODER_ERROR
IJKMEDIA: FFP_MSG_VIDEO_DECODER_ERROR:
TXCVodVideoView: onVideoDecoderError
TXCVodVideoView: sendSimpleEvent 2106 decode fail

**Comment by wzyzb** [comment]
这个错误是解码出错了，是必现的吗？可以把视频提供一下

**Comment by zhangshaobo87** [comment]
是必现的，能加下你的联系方式吗，我把链接发给你，因为是收费课程的视频链接，不好在这里发出来

**Comment by wzyzb** [comment]
githib 可以私信吗？

**Comment by zhangshaobo87** [comment]
你加下我QQ可以么，在github上我没找到哪里私信啊    977122009

**Comment by wzyzb** [comment]
发我邮箱 wzyzb@qq.com

**Comment by LeiHolmes** [comment]
您好，请问解决了吗？
