### ISSUE TITLE
小小建议

### ISSUE THREAD

**Issue by eekidu** [tencentyun/SuperPlayer_Android#50]
1、LiteAVSDK可否提供在线的依赖方式，手动下载aar更新，太麻烦，不够优雅。
2、LiteAVSDK   .class无关联源码，能关联源码，查看起来就更好了。

**Comment by wzyzb** [comment]
你好，我们后面考虑下提供在线下载方式

**Comment by eekidu** [comment]
LiteAVSDK 中的类，现在我是通过关联javadoc，进行查看的。不知道是否有.java格式的源码提供，方便查看。
![image](https://user-images.githubusercontent.com/12985157/69705928-86271780-1131-11ea-9e8b-466e07c5022f.png)

**Comment by wzyzb** [comment]
sdk是不开源的

**Comment by eekidu** [comment]
了解了，多谢！
