### ISSUE TITLE
华为手机点播播放失败

### ISSUE THREAD

**Issue by zouwansheng** [tencentyun/SuperPlayer_Android#51]
目前试了两台华为手机，直播都可以，点播不可以播放，都是播放失败，
E/IJKMEDIA: ijkio:cache:ffio:http://XXX/room000001000001/2019-11-22-10-58-27_2019-11-22-11-49-52.mp4: Operation not permitted
I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [10244]
E/com.tencent.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
E/TXCVodVideoView: onError: -10000,0

**Comment by wzyzb** [comment]
好的 我们尽快看下

**Comment by zouwansheng** [comment]
好的 同样的视频地址其他手机完全没问题 目前就发现华为无法播放

**Comment by zouwansheng** [comment]
目前试了另一个视频地址，华为可以播放了，难道是视频地址原因？但是别的手机为什么正常播放

**Comment by wzyzb** [comment]
你清理下缓存试试
