### ISSUE TITLE
SIGABRT

### ISSUE THREAD

**Issue by chaoDream** [tencentyun/SuperPlayer_Android#53]
#01 pc 00035021 /data/data/tojoy.com.tojoytv/libperfa_arm.so [armeabi-v7a]
#00 pc 0001d796 /system/lib/libc.so (abort+57) [armeabi-v7a]
2 #01 pc 00035021 /data/data/********/libperfa_arm.so [armeabi-v7a]
3 #02 pc 0003b633 /data/data/********/libperfa_arm.so [armeabi-v7a]
4 #03 pc 0003b47f /data/data/********/libperfa_arm.so [armeabi-v7a]
5 #04 pc 00029efb /data/data/********/libperfa_arm.so [armeabi-v7a]
6 #05 pc 00069875 /system/lib/libopenjdkjvmti.so (voidenjdkjvmti::EventHandler*, art::Thread*, openjdkjvmti::ArtClassDefinition*)+1472) [armeabi-v7a]
7 #06 pc 0006a0c3 /system/lib/libopenjdkjvmti.so (openjdkjvmti::Transformer::RetransformClasses(openjdkjvmti::ArtJvmTiEnv*, openjdkjvmti::EventHandler*, art::Runtime*, art::Thread*, int, _jclass* const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*)+442) [armeabi-v7a]
8 #07 pc 0002bd95 /system/lib/libopenjdkjvmti.so [armeabi-v7a]
9 #08 pc 0002acd7 /data/data/********/libperfa_arm.so (Agent_OnAttach+370) [armeabi-v7a]
10 #09 pc 0039be07 /system/lib/libart.so (art::ti::AgentSpec::DoLoadHelper(_JNIEnv*, bool, _jobject*, int*, art::ti::LoadError*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*)+482) [armeabi-v7a]
11 #10 pc 0039c3c5 /system/lib/libart.so (art::ti::AgentSpec::Attach(_JNIEnv*, _jobject*, int*, art::ti::LoadError*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*)+60) [armeabi-v7a]
12 #11 pc 0036bd7f /system/lib/libart.so (art::Runtime::AttachAgent(_JNIEnv*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, _jobject*)+982) [armeabi-v7a]
13 #12 pc 002f3009 /system/lib/libart.so (art::ThreadDexHotfixChecker(void*)+804) [armeabi-v7a]
14 #13 pc 0008e00b /system/framework/arm/boot-core-libart.oat [armeabi]
15 java:
16 dalvik.system.VMDebug.attachAgent(VMDebug.java:547)
17 android.app.ActivityThread.attemptAttachAgent(ActivityThread.java:3920)
18 android.app.ActivityThread.handleAttachAgent(ActivityThread.java:3930)
19 android.app.ActivityThread$H.handleMessage(ActivityThread.java:2180)
20 android.os.Handler.dispatchMessage(Handler.java:112)
21 android.os.Looper.loop(Looper.java:216)
22 android.app.ActivityThread.main(ActivityThread.java:7625)
23 java.lang.reflect.Method.invoke(Native Method)
24 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
25 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

这种一般都是什么情况下回出现，或者我们有什么回避方案没

**Comment by wzyzb** [comment]
你这个没看到与播放器相关的堆栈哦
