### ISSUE TITLE
有的m3u8播放不了

### ISSUE THREAD

**Issue by Mitaxing** [tencentyun/SuperPlayer_Android#54]
SDK：6.8.7969
url：https://bobo.kkpp.space/20180103/2KZkZ2bv/hls/index.m3u8
使用其他播放器是可以播放的
日志如下
`V/IJKMEDIA: setDataSource: path ijkhlscache:https://bobo.kkpp.space/20180103/2KZkZ2bv/hls/index.m3u8
D/IJKMEDIA: ffpipeline_set_surface()
W/com.tencent.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
D/IJKMEDIA: ffpipeline_set_volume
D/IJKMEDIA: ffpipeline_set_volume
I/IJKMEDIA: SDL_RunThread: [4056] ff_msg_loop
I/IJKMEDIA: SDL_RunThread: [4057] ff_vout
I/IJKMEDIA: SDL_RunThread: [4058] ff_read
D/IJKMEDIA: ijktsdb:close database
D/IJKMEDIA: ijktsdb:Opened database successfully, total 0
E/IJKMEDIA: ijkhlscache:https://bobo.kkpp.space/20180103/2KZkZ2bv/index.m3u8?sign=1d96286ad29ac7d4714aefb7b3c5eb56: Immediate exit reque
I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [4048]
E/IJKMEDIA: SDL_JNI_ThreadDestroyed: [4049] didn't call SDL_JNI_DetachThreadEnv() explicity
D/IJKMEDIA: diskdb_select (https://bobo.kkpp.space/20180103/2KZkZ2bv/hls/index.m3u8, 61031)
E/IJKMEDIA: ijktsdb:get database 1
W/IJKMEDIA: HTTP error 404 Not Found
D/IJKMEDIA: ijktsdb:retain 1
E/IJKMEDIA: Unable to open key file ijkhlscache:https://bobo.kkpp.space/20180103/2KZkZ2bv/hls/ijkhlscache:key.key
E/IJKMEDIA: ijktsdb:get database 1
E/IJKMEDIA: Error when loading first segment 'ijkhlscache:https://bobo.kkpp.space/20180103/2KZkZ2bv/hls/Sy792552000.ts'
D/IJKMEDIA: https://bobo.kkpp.space/20180103/2KZkZ2bv/hls/Sy792552000.ts not insert!
D/IJKMEDIA: ijktsdb:retain 1
D/IJKMEDIA: ijktsdb:close database
E/IJKMEDIA: ijkhlscache:https://bobo.kkpp.space/20180103/2KZkZ2bv/hls/index.m3u8: Invalid data found when processing input
I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [4058]
I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [4056]
E/com.tencent.ijk.media.player.IjkMediaPlayer: Error (-10000,0)`

**Comment by wzyzb** [comment]
你试试把播放器的缓存清除后播放看下

**Comment by Mitaxing** [comment]
清除所有缓存后仍播放不了

**Comment by wzyzb** [comment]
你的播放器缓存目录设置在哪个路径？

**Comment by Mitaxing** [comment]
没有设置缓存路径，有将应用缓存全部清理，再次播放失败

**Comment by wzyzb** [comment]
我这边试了可以播放
