### ISSUE TITLE
无缝切换清晰度，不支持MP4格式吗？

### ISSUE THREAD

**Issue by eekidu** [tencentyun/SuperPlayer_Android#57]
`      SuperPlayerModel model = new SuperPlayerModel();
        model.multiURLs = new ArrayList<>();
        model.multiURLs.add(new SuperPlayerModel.SuperPlayerURL("http://1252463788.vod2.myqcloud.com/95576ef5vodtransgzp1252463788/e1ab85305285890781763144364/v.f10.mp4", "流畅"));
        model.multiURLs.add(new SuperPlayerModel.SuperPlayerURL("http://1252463788.vod2.myqcloud.com/95576ef5vodtransgzp1252463788/e1ab85305285890781763144364/v.f20.mp4", "标清"));
        model.multiURLs.add(new SuperPlayerModel.SuperPlayerURL("http://1252463788.vod2.myqcloud.com/95576ef5vodtransgzp1252463788/e1ab85305285890781763144364/v.f30.mp4", "高清"));
        model.playDefaultIndex = 1;// 默认播放标清`

我用以上代码测试无缝切换清晰度，
` mVodPlayer.setBitrateIndex(quality.index);`
播放器中执行了该语句，但是好像不起作用，清晰度并没有改变，是不支持MP4格式吗？
以上代码就是你们文档中的代码 [文档](https://cloud.tencent.com/document/product/881/20213#.E5.A4.9A.E6.B8.85.E6.99.B0.E5.BA.A6)

**Comment by wzyzb** [comment]
我了解下

**Comment by echoYZ1208** [comment]
@eekidu 是的，无缝切换清晰度仅支持多码流的m3u8格式(通过setBitrateIndex实现)，不支持mp4格式，如果是mp4格式，只能通过设置重新设置url后播放。

**Comment by eekidu** [comment]
那文档中 示例代码就有问题了，并且SuperPlayer中onQualitySelect(TCVideoQulity quality)也不准确！

**Comment by echoYZ1208** [comment]
@eekidu 您好，这里需要详细解释下：超级播放器中的“无缝切换清晰度”具体是指**直播**的清晰度，超级播放器的点播功能不支持无缝切换清晰度，这些在文档开头已经说明：“同时还支持直播流（FLV + RTMP）播放，具备首屏秒开、低延迟的优点，清晰度无缝切换、直播时移等高级能力。”

**Comment by echoYZ1208** [comment]
您好，这里需要详细解释下，超级播放器中的“无缝切换清晰度”是指切换**直播**的清晰度，而超级播放器的点播功能不支持无缝切换清晰度，这里在官网文档开头有说明：
“同时还支持直播流（FLV + RTMP）播放，具备首屏秒开、低延迟的优点，清晰度无缝切换、直播时移等高级能力。”
而上面的示例代码展示的是多url多码率(多清晰度)的点播(而非直播)的播放方式，自然不支持无缝切换清晰度，点播的三种播放方式具体可以参考源码中的SuperPlayerModel.java，其中有详细的注释说明。
另外，如需实现类似于无缝切换切换清晰度的点播需求，可以通过点播播放器的预加载实现，具体可以参考官网文档：https://cloud.tencent.com/document/product/881/20216#step-10.3A-.E9.A2.84.E5.8A.A0.E8.BD.BD

**Comment by eekidu** [comment]
好，无缝切换清晰度问题我理解了。
代码有一点疑问，
SuperPlayerView中通过
`playWithModel(final SuperPlayerModel modelV3) `进行多清晰度视频播放，
`
其中
` videoQualities.add(new TCVideoQulity(i++, superPlayerURL.qualityName, superPlayerURL.url));`
并没有对index进行直播与点播的区分。点播的indexl=-1，而不应该时i++吧。
要不然，清晰度切换的回调中，不会走 ==-1分支的
`  if (mCurrentPlayType == SuperPlayerConst.PLAYTYPE_VOD) {
                if (mVodPlayer != null) {
                    if (quality.index == -1) {
                        // 说明是非多bitrate的m3u8子流，需要手动seek
                        float currentTime = mVodPlayer.getCurrentPlaybackTime();
                        mVodPlayer.stopPlay(true);
                        TXCLog.i(TAG, "onQualitySelect quality.url:" + quality.url);
                        mVodPlayer.setStartTime(currentTime);
                        mVodPlayer.startPlay(quality.url);
                    } else {
                        TXCLog.i(TAG, "setBitrateIndex quality.index:" + quality.index);
                        // 说明是多bitrate的m3u8子流，会自动无缝seek
                        mVodPlayer.setBitrateIndex(quality.index);
                    }
                }
            } `

**Comment by echoYZ1208** [comment]
您好，这里确实有问题，感谢反馈，我们尽快修复！

**Comment by zhangshaobo87** [comment]
我看了最新的代码 这里好像还是没有修复呀
