### ISSUE TITLE
添加布局异常

### ISSUE THREAD

**Issue by Joslyn-Chen** [tencentyun/SuperPlayer_Android#59]
引入的是：LiteAVSDK_Player.aar和libsuperplayer.aar。
` 
android.view.InflateException: Binary XML file line #50: Binary XML file line #50: Error inflating class com.tencent.liteav.demo.play.SuperPlayerView

Binary XML file line #50: Error inflating class com.tencent.liteav.demo.play.SuperPlayerView

Binary XML file line #17: Error inflating class com.tencent.liteav.demo.play.controller.TCVodControllerLarge

Binary XML file line #171: Error inflating class com.tencent.liteav.demo.play.view.TCVodMoreView

AndroidRuntime:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)

Caused by: java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to android.app.Activity
        at com.tencent.liteav.demo.play.view.TCVodMoreView.updateCurrentLight(TCVodMoreView.java:104)
`

**Comment by wzyzb** [comment]
引入出错了吧，这个错误应该是找不到相应的类

**Comment by Joslyn-Chen** [comment]
引入应该没问题吧，我后来把libsuperplayer源码拉下来改了才可以。
出错的地方：TCVodMoreView：`Activity activity = (Activity) mContext;`

**Comment by jiangmw** [comment]
到现在还没修复这个bug

**Comment by Code-Yeong** [comment]
遇到了一样的问题......
