### ISSUE TITLE
初始化播放器亮度为最亮,请问如何修改

### ISSUE THREAD

**Issue by WZRRRRRR** [tencentyun/SuperPlayer_Android#6]
如题

**Comment by huluxia** [comment]
求同

**Comment by AlphaHans** [comment]
您好，可以修改https://github.com/tencentyun/SuperPlayer_Android/blob/master/lib_tcsuperplayer/src/main/java/com/tencent/liteav/demo/play/utils/VideoGestureUtil.java
此类达到您的要求。
