### ISSUE TITLE
这个项目中的直播功能，使用是否会产生费用？

### ISSUE THREAD

**Issue by imuzi** [tencentyun/SuperPlayer_Android#60]
Ios github地址并没有移动直播的功能，是否使用移动直播会导致14天后不能使用的情况。@

**Comment by echoYZ1208** [comment]
ios和Android的超级播放器的功能是一样的，并且都是开源的，使用不会产生任何费用，关于播放器具体可以查看官网文档：https://cloud.tencent.com/document/product/881/20213
