### ISSUE TITLE
TXCLog异常

### ISSUE THREAD

**Issue by piratejason** [tencentyun/SuperPlayer_Android#61]
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2793)
--
3 ......
4 Caused by:
5 java.lang.NullPointerException:Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
6 com.tencent.liteav.basic.log.TXCLog.init(TXCLog.java:46)
7 com.tencent.rtmp.TXVodPlayer.<init>(TXVodPlayer.java:90)

**Comment by echoYZ1208** [comment]
您好，请问这是什么情况下发生的？

**Comment by piratejason** [comment]
> 您好，请问这是什么情况下发生的？

我集成了qqbugly  在崩溃列表里看到的
具体在什么情况下发生的 我也不知道

**Comment by piratejason** [comment]
> > 您好，请问这是什么情况下发生的？
> 
> 我集成了qqbugly 在崩溃列表里看到的
> 具体在什么情况下发生的 我也不知道

只能说在初始化视频播放器的时候发生

**Comment by whalehe** [comment]
您好，可以使用我们最新版本，看看有无此问题
