### ISSUE TITLE
如何不让屏幕自动变亮呢？

### ISSUE THREAD

**Issue by maple023** [tencentyun/SuperPlayer_Android#63]

**Comment by Newwaygo** [comment]
+1

**Comment by Iamivan1996** [comment]
在TcVodMoreView.java 找到updateCurrentLight的function,然後把有關的code拿走
`  if (params.screenBrightness == -1) {
            mSeekBarLight.setProgress(10);
            return;
        }
        mSeekBarLight.setProgress((int) (params.screenBrightness * 100)`

這裏-1 的意思是BRIGHTNESS_OVERRIDE_NONE, 所以當override none時，player會自動調亮
