### ISSUE TITLE
怎么监听视频在缓冲中？

### ISSUE THREAD

**Issue by Newwaygo** [tencentyun/SuperPlayer_Android#64]
现在问题是视频缓冲时，退出视频播放的Activity,缓冲完成后视频又开始播放，没法关闭。
LiteAVSDK_Player_6.7.7754.aar

**Comment by wzyzb** [comment]
关闭activity之后需要关闭播放器

**Comment by Iamivan1996** [comment]
onPlayEvent的回调中， PLAY_EVT_PLAY_LOADING寫著是缓冲开始, 應該是這個

**Comment by wzyzb** [comment]
> onPlayEvent的回调中， PLAY_EVT_PLAY_LOADING寫著是缓冲开始, 應該是這個， 而PLAY_EVT_VOD_LOADING_END是缓冲結束

对的，onPlayEvent中有相应回调
