### ISSUE TITLE
多URL切换清晰度经常切换不成功，能切换成功的时候也需要等差不多10s左右才能切换成功

### ISSUE THREAD

**Issue by zhangshaobo87** [tencentyun/SuperPlayer_Android#66]
多URL切换清晰度经常切换不成功，我在自己的app测试的时候10次至少有7次不能切换成功，剩余几次即使能切换成功也需要等差不多10s左右才能切换成功，我下了demo apk 发现demo里边也会有切换不成功的情况，但绝大部分还是能切换成功的，demo里边的切换清晰度体验要比我自己的app好很多，请问有什么办法优化吗？
![image](https://user-images.githubusercontent.com/17812840/71757702-9ec5e280-2ed2-11ea-8343-ad99ff51cb8f.png)

**Comment by wzyzb** [comment]
你们的视频存储在腾讯云吗？ 你参考下demo代码的多清晰度切换
