### ISSUE TITLE
通过setPlayerView()设置TXCloudVideoView的警告，IllegalArgumentException

### ISSUE THREAD

**Issue by eekidu** [tencentyun/SuperPlayer_Android#69]
想要实现的效果是这样的，视频在A界面播放，从A界面跳转到B界面，B界面继续播放，不中断，不重新加载。
我现在的实现方式是，一个单例的TXVodPlayer，然后通过setPlayerView(TXCloudVideoView)，切换展示的View。效果能实现，只不过有如下的警告
![image](https://user-images.githubusercontent.com/12985157/72329864-7c14a480-36f0-11ea-8d9b-eeef2cab7f14.png)
想要确认一下，这么使用有什么问题吗？

**Comment by wzyzb** [comment]
你更新下最新版本看是否还有这个警告，6.9应该处理了这个问题

**Comment by eekidu** [comment]
好像还是会有，DEMO中触发小窗显示也一样，也会提示该警告信息。

**Comment by whalehe** [comment]
您好，可以更新下我们最新版本7.4，如果还有问题，烦请附上日志或者截图信息。
