### ISSUE TITLE
播放器设置header

### ISSUE THREAD

**Issue by huluxia** [tencentyun/SuperPlayer_Android#7]
请问播放器怎么设置header

 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by AlphaHans** [comment]
mLivePlayConfig = new TXLivePlayConfig();
        // HashMap<String, String> headers = new HashMap<>();
        // headers.put("Referer", "qcloud.com");
        // mLivePlayConfig.setHeaders(headers);

直播播放器的config中可设置。 您可在SuperPlayerView初始化直播播放器时候设置
