### ISSUE TITLE
能不能提供一个在列表中点击播放滑出暂停例子，方便集成！

### ISSUE THREAD

**Issue by 15201296725** [tencentyun/SuperPlayer_Android#73]

**Comment by MoYuFly** [comment]
为何关闭了呢，有列子，提供一下，谢谢哦。

**Comment by 15201296725** [comment]
应该是作者关闭了，上次看到没有本想问下 然后看到关闭了。现在都是自己写。



发件人：卜鸣扬
邮箱：1925350623@qq.com
联系方式：15201296725


&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"MoYu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 上午10:59
收件人:&nbsp;"tencentyun/SuperPlayer_Android"<SuperPlayer_Android@noreply.github.com&gt;;
抄送:&nbsp;"北京 -流年"<1925350623@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [tencentyun/SuperPlayer_Android] 能不能提供一个在列表中点击播放滑出暂停例子，方便集成！ (#73)





 
为何关闭了呢，有列子，提供一下，谢谢哦。

**Comment by MoYuFly** [comment]
所以你目前的实现方案呢，我们目前没有使用这个超级播放器，自己封装的播放器和播放view，在需要播放的地方，放置一个空的view，每次播放，把播放器add进去，不在播放的时候，在remove掉。

**Comment by 15201296725** [comment]
嗯 ，我采用的是 显示 隐藏&nbsp;
&nbsp;

发件人：卜鸣扬
邮箱：1925350623@qq.com
联系方式：15201296725


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "MoYu"<notifications@github.com&gt;; 
发送时间: 2020年3月26日(星期四) 中午11:04
收件人: "tencentyun/SuperPlayer_Android"<SuperPlayer_Android@noreply.github.com&gt;; 
抄送: "android 菜菜"<1925350623@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [tencentyun/SuperPlayer_Android] 能不能提供一个在列表中点击播放滑出暂停例子，方便集成！ (#73)





 
所以你目前的实现方案呢，我们目前没有使用这个超级播放器，自己封装的播放器和播放view，在需要播放的地方，放置一个空的view，每次播放，把播放器add进去，不在播放的时候，在remove掉。

**Comment by MoYuFly** [comment]
那你是在每个item上面都放置了 superplayerview？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"卜鸣扬"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 中午12:34
收件人:&nbsp;"tencentyun/SuperPlayer_Android"<SuperPlayer_Android@noreply.github.com&gt;;
抄送:&nbsp;"782771031"<782771031@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [tencentyun/SuperPlayer_Android] 能不能提供一个在列表中点击播放滑出暂停例子，方便集成！ (#73)





 嗯 ，我采用的是 显示 隐藏&amp;nbsp; 
 &amp;nbsp; 
 
 发件人：卜鸣扬 
 邮箱：1925350623@qq.com 
 联系方式：15201296725 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "MoYu"<notifications@github.com&amp;gt;;  
 发送时间: 2020年3月26日(星期四) 中午11:04 
 收件人: "tencentyun/SuperPlayer_Android"<SuperPlayer_Android@noreply.github.com&amp;gt;;  
 抄送: "android 菜菜"<1925350623@qq.com&amp;gt;; "Author"<author@noreply.github.com&amp;gt;;  
 主题: Re: [tencentyun/SuperPlayer_Android] 能不能提供一个在列表中点击播放滑出暂停例子，方便集成！ (#73) 
 
 
 
 
 
   
 所以你目前的实现方案呢，我们目前没有使用这个超级播放器，自己封装的播放器和播放view，在需要播放的地方，放置一个空的view，每次播放，把播放器add进去，不在播放的时候，在remove掉。

**Comment by 15201296725** [comment]
嗯 是的&nbsp;

发件人：卜鸣扬
邮箱：1925350623@qq.com
联系方式：15201296725


&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"MoYu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 中午12:35
收件人:&nbsp;"tencentyun/SuperPlayer_Android"<SuperPlayer_Android@noreply.github.com&gt;;
抄送:&nbsp;"android 菜菜"<1925350623@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [tencentyun/SuperPlayer_Android] 能不能提供一个在列表中点击播放滑出暂停例子，方便集成！ (#73)





 那你是在每个item上面都放置了 superplayerview？ 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"卜鸣扬"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年3月26日(星期四) 中午12:34 
 收件人:&amp;nbsp;"tencentyun/SuperPlayer_Android"<SuperPlayer_Android@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"782771031"<782771031@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [tencentyun/SuperPlayer_Android] 能不能提供一个在列表中点击播放滑出暂停例子，方便集成！ (#73) 
 
 
 
 
 
  嗯 ，我采用的是 显示 隐藏&amp;amp;nbsp;  
  &amp;amp;nbsp;  
   
  发件人：卜鸣扬  
  邮箱：1925350623@qq.com  
  联系方式：15201296725  
   
   
  &amp;amp;nbsp;  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: "MoYu"<notifications@github.com&amp;amp;gt;;   
  发送时间: 2020年3月26日(星期四) 中午11:04  
  收件人: "tencentyun/SuperPlayer_Android"<SuperPlayer_Android@noreply.github.com&amp;amp;gt;;   
  抄送: "android 菜菜"<1925350623@qq.com&amp;amp;gt;; "Author"<author@noreply.github.com&amp;amp;gt;;   
  主题: Re: [tencentyun/SuperPlayer_Android] 能不能提供一个在列表中点击播放滑出暂停例子，方便集成！ (#73)  
   
   
   
   
   
     
  所以你目前的实现方案呢，我们目前没有使用这个超级播放器，自己封装的播放器和播放view，在需要播放的地方，放置一个空的view，每次播放，把播放器add进去，不在播放的时候，在remove掉。

**Comment by MoYuFly** [comment]
好吧，我们两边的实现方式不一样。这样，你每个item播放时，在适配器中，停止其他item的播放器吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"卜鸣扬"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 中午12:37
收件人:&nbsp;"tencentyun/SuperPlayer_Android"<SuperPlayer_Android@noreply.github.com&gt;;
抄送:&nbsp;"782771031"<782771031@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [tencentyun/SuperPlayer_Android] 能不能提供一个在列表中点击播放滑出暂停例子，方便集成！ (#73)





 嗯 是的&amp;nbsp; 
 
 发件人：卜鸣扬 
 邮箱：1925350623@qq.com 
 联系方式：15201296725 
 
 
 &amp;nbsp; 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"MoYu"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年3月26日(星期四) 中午12:35 
 收件人:&amp;nbsp;"tencentyun/SuperPlayer_Android"<SuperPlayer_Android@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"android 菜菜"<1925350623@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [tencentyun/SuperPlayer_Android] 能不能提供一个在列表中点击播放滑出暂停例子，方便集成！ (#73) 
 
 
 
 
 
  那你是在每个item上面都放置了 superplayerview？  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:&amp;amp;nbsp;"卜鸣扬"<notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年3月26日(星期四) 中午12:34  
  收件人:&amp;amp;nbsp;"tencentyun/SuperPlayer_Android"<SuperPlayer_Android@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"782771031"<782771031@qq.com&amp;amp;gt;;"Comment"<comment@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [tencentyun/SuperPlayer_Android] 能不能提供一个在列表中点击播放滑出暂停例子，方便集成！ (#73)  
   
   
   
   
   
   嗯 ，我采用的是 显示 隐藏&amp;amp;amp;nbsp;   
   &amp;amp;amp;nbsp;   
     
   发件人：卜鸣扬   
   邮箱：1925350623@qq.com   
   联系方式：15201296725   
     
     
   &amp;amp;amp;nbsp;   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人: "MoYu"<notifications@github.com&amp;amp;amp;gt;;    
   发送时间: 2020年3月26日(星期四) 中午11:04   
   收件人: "tencentyun/SuperPlayer_Android"<SuperPlayer_Android@noreply.github.com&amp;amp;amp;gt;;    
   抄送: "android 菜菜"<1925350623@qq.com&amp;amp;amp;gt;; "Author"<author@noreply.github.com&amp;amp;amp;gt;;    
   主题: Re: [tencentyun/SuperPlayer_Android] 能不能提供一个在列表中点击播放滑出暂停例子，方便集成！ (#73)   
     
     
     
     
     
       
   所以你目前的实现方案呢，我们目前没有使用这个超级播放器，自己封装的播放器和播放view，在需要播放的地方，放置一个空的view，每次播放，把播放器add进去，不在播放的时候，在remove掉。

**Comment by 15201296725** [comment]
停止啊 不然声音不是乱了吗&nbsp;



发件人：卜鸣扬
邮箱：1925350623@qq.com
联系方式：15201296725


&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"MoYu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 中午12:38
收件人:&nbsp;"tencentyun/SuperPlayer_Android"<SuperPlayer_Android@noreply.github.com&gt;;
抄送:&nbsp;"android 菜菜"<1925350623@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [tencentyun/SuperPlayer_Android] 能不能提供一个在列表中点击播放滑出暂停例子，方便集成！ (#73)





 好吧，我们两边的实现方式不一样。这样，你每个item播放时，在适配器中，停止其他item的播放器吗？ 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"卜鸣扬"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年3月26日(星期四) 中午12:37 
 收件人:&amp;nbsp;"tencentyun/SuperPlayer_Android"<SuperPlayer_Android@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"782771031"<782771031@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [tencentyun/SuperPlayer_Android] 能不能提供一个在列表中点击播放滑出暂停例子，方便集成！ (#73) 
 
 
 
 
 
  嗯 是的&amp;amp;nbsp;  
   
  发件人：卜鸣扬  
  邮箱：1925350623@qq.com  
  联系方式：15201296725  
   
   
  &amp;amp;nbsp;  
   
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:&amp;amp;nbsp;"MoYu"<notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年3月26日(星期四) 中午12:35  
  收件人:&amp;amp;nbsp;"tencentyun/SuperPlayer_Android"<SuperPlayer_Android@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"android 菜菜"<1925350623@qq.com&amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [tencentyun/SuperPlayer_Android] 能不能提供一个在列表中点击播放滑出暂停例子，方便集成！ (#73)  
   
   
   
   
   
   那你是在每个item上面都放置了 superplayerview？   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:&amp;amp;amp;nbsp;"卜鸣扬"<notifications@github.com&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2020年3月26日(星期四) 中午12:34   
   收件人:&amp;amp;amp;nbsp;"tencentyun/SuperPlayer_Android"<SuperPlayer_Android@noreply.github.com&amp;amp;amp;gt;;   
   抄送:&amp;amp;amp;nbsp;"782771031"<782771031@qq.com&amp;amp;amp;gt;;"Comment"<comment@noreply.github.com&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [tencentyun/SuperPlayer_Android] 能不能提供一个在列表中点击播放滑出暂停例子，方便集成！ (#73)   
     
     
     
     
     
    嗯 ，我采用的是 显示 隐藏&amp;amp;amp;amp;nbsp;    
    &amp;amp;amp;amp;nbsp;    
       
    发件人：卜鸣扬    
    邮箱：1925350623@qq.com    
    联系方式：15201296725    
       
       
    &amp;amp;amp;amp;nbsp;    
       
       
       
       
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------    
    发件人: "MoYu"<notifications@github.com&amp;amp;amp;amp;gt;;     
    发送时间: 2020年3月26日(星期四) 中午11:04    
    收件人: "tencentyun/SuperPlayer_Android"<SuperPlayer_Android@noreply.github.com&amp;amp;amp;amp;gt;;     
    抄送: "android 菜菜"<1925350623@qq.com&amp;amp;amp;amp;gt;; "Author"<author@noreply.github.com&amp;amp;amp;amp;gt;;     
    主题: Re: [tencentyun/SuperPlayer_Android] 能不能提供一个在列表中点击播放滑出暂停例子，方便集成！ (#73)    
       
       
       
       
       
         
    所以你目前的实现方案呢，我们目前没有使用这个超级播放器，自己封装的播放器和播放view，在需要播放的地方，放置一个空的view，每次播放，把播放器add进去，不在播放的时候，在remove掉。

**Comment by MoYuFly** [comment]
那有没有对内存性能有影响，我看那个封装的playerview里面控件很多。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"卜鸣扬"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 中午12:37
收件人:&nbsp;"tencentyun/SuperPlayer_Android"<SuperPlayer_Android@noreply.github.com&gt;;
抄送:&nbsp;"782771031"<782771031@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [tencentyun/SuperPlayer_Android] 能不能提供一个在列表中点击播放滑出暂停例子，方便集成！ (#73)





 嗯 是的&amp;nbsp; 
 
 发件人：卜鸣扬 
 邮箱：1925350623@qq.com 
 联系方式：15201296725 
 
 
 &amp;nbsp; 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"MoYu"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年3月26日(星期四) 中午12:35 
 收件人:&amp;nbsp;"tencentyun/SuperPlayer_Android"<SuperPlayer_Android@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"android 菜菜"<1925350623@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [tencentyun/SuperPlayer_Android] 能不能提供一个在列表中点击播放滑出暂停例子，方便集成！ (#73) 
 
 
 
 
 
  那你是在每个item上面都放置了 superplayerview？  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:&amp;amp;nbsp;"卜鸣扬"<notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年3月26日(星期四) 中午12:34  
  收件人:&amp;amp;nbsp;"tencentyun/SuperPlayer_Android"<SuperPlayer_Android@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"782771031"<782771031@qq.com&amp;amp;gt;;"Comment"<comment@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [tencentyun/SuperPlayer_Android] 能不能提供一个在列表中点击播放滑出暂停例子，方便集成！ (#73)  
   
   
   
   
   
   嗯 ，我采用的是 显示 隐藏&amp;amp;amp;nbsp;   
   &amp;amp;amp;nbsp;   
     
   发件人：卜鸣扬   
   邮箱：1925350623@qq.com   
   联系方式：15201296725   
     
     
   &amp;amp;amp;nbsp;   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人: "MoYu"<notifications@github.com&amp;amp;amp;gt;;    
   发送时间: 2020年3月26日(星期四) 中午11:04   
   收件人: "tencentyun/SuperPlayer_Android"<SuperPlayer_Android@noreply.github.com&amp;amp;amp;gt;;    
   抄送: "android 菜菜"<1925350623@qq.com&amp;amp;amp;gt;; "Author"<author@noreply.github.com&amp;amp;amp;gt;;    
   主题: Re: [tencentyun/SuperPlayer_Android] 能不能提供一个在列表中点击播放滑出暂停例子，方便集成！ (#73)   
     
     
     
     
     
       
   所以你目前的实现方案呢，我们目前没有使用这个超级播放器，自己封装的播放器和播放view，在需要播放的地方，放置一个空的view，每次播放，把播放器add进去，不在播放的时候，在remove掉。

**Comment by 15201296725** [comment]
嗯 目前我也没想好更好的实现，如果你有例子 可以提供一份 参考！



发件人：卜鸣扬
邮箱：1925350623@qq.com
联系方式：15201296725


&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"MoYu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 中午12:44
收件人:&nbsp;"tencentyun/SuperPlayer_Android"<SuperPlayer_Android@noreply.github.com&gt;;
抄送:&nbsp;"android 菜菜"<1925350623@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [tencentyun/SuperPlayer_Android] 能不能提供一个在列表中点击播放滑出暂停例子，方便集成！ (#73)





 那有没有对内存性能有影响，我看那个封装的playerview里面控件很多。 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"卜鸣扬"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年3月26日(星期四) 中午12:37 
 收件人:&amp;nbsp;"tencentyun/SuperPlayer_Android"<SuperPlayer_Android@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"782771031"<782771031@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [tencentyun/SuperPlayer_Android] 能不能提供一个在列表中点击播放滑出暂停例子，方便集成！ (#73) 
 
 
 
 
 
  嗯 是的&amp;amp;nbsp;  
   
  发件人：卜鸣扬  
  邮箱：1925350623@qq.com  
  联系方式：15201296725  
   
   
  &amp;amp;nbsp;  
   
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:&amp;amp;nbsp;"MoYu"<notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年3月26日(星期四) 中午12:35  
  收件人:&amp;amp;nbsp;"tencentyun/SuperPlayer_Android"<SuperPlayer_Android@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"android 菜菜"<1925350623@qq.com&amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [tencentyun/SuperPlayer_Android] 能不能提供一个在列表中点击播放滑出暂停例子，方便集成！ (#73)  
   
   
   
   
   
   那你是在每个item上面都放置了 superplayerview？   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:&amp;amp;amp;nbsp;"卜鸣扬"<notifications@github.com&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2020年3月26日(星期四) 中午12:34   
   收件人:&amp;amp;amp;nbsp;"tencentyun/SuperPlayer_Android"<SuperPlayer_Android@noreply.github.com&amp;amp;amp;gt;;   
   抄送:&amp;amp;amp;nbsp;"782771031"<782771031@qq.com&amp;amp;amp;gt;;"Comment"<comment@noreply.github.com&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [tencentyun/SuperPlayer_Android] 能不能提供一个在列表中点击播放滑出暂停例子，方便集成！ (#73)   
     
     
     
     
     
    嗯 ，我采用的是 显示 隐藏&amp;amp;amp;amp;nbsp;    
    &amp;amp;amp;amp;nbsp;    
       
    发件人：卜鸣扬    
    邮箱：1925350623@qq.com    
    联系方式：15201296725    
       
       
    &amp;amp;amp;amp;nbsp;    
       
       
       
       
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------    
    发件人: "MoYu"<notifications@github.com&amp;amp;amp;amp;gt;;     
    发送时间: 2020年3月26日(星期四) 中午11:04    
    收件人: "tencentyun/SuperPlayer_Android"<SuperPlayer_Android@noreply.github.com&amp;amp;amp;amp;gt;;     
    抄送: "android 菜菜"<1925350623@qq.com&amp;amp;amp;amp;gt;; "Author"<author@noreply.github.com&amp;amp;amp;amp;gt;;     
    主题: Re: [tencentyun/SuperPlayer_Android] 能不能提供一个在列表中点击播放滑出暂停例子，方便集成！ (#73)    
       
       
       
       
       
         
    所以你目前的实现方案呢，我们目前没有使用这个超级播放器，自己封装的播放器和播放view，在需要播放的地方，放置一个空的view，每次播放，把播放器add进去，不在播放的时候，在remove掉。

**Comment by MoYuFly** [comment]
我这边目前的实现是，全局只有一个播放器view，在要播放的地方，放置一个空的view，需要播放的时候，就把全局播放器view add到这个view里面，如果其他地方需要播放，就把这个播放器view的父view 清空，然后把它放到新的地方，目前是这样控制的。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"卜鸣扬"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 中午12:53
收件人:&nbsp;"tencentyun/SuperPlayer_Android"<SuperPlayer_Android@noreply.github.com&gt;;
抄送:&nbsp;"782771031"<782771031@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [tencentyun/SuperPlayer_Android] 能不能提供一个在列表中点击播放滑出暂停例子，方便集成！ (#73)





 嗯 目前我也没想好更好的实现，如果你有例子 可以提供一份 参考！ 
 
 
 
 发件人：卜鸣扬 
 邮箱：1925350623@qq.com 
 联系方式：15201296725 
 
 
 &amp;nbsp; 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"MoYu"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年3月26日(星期四) 中午12:44 
 收件人:&amp;nbsp;"tencentyun/SuperPlayer_Android"<SuperPlayer_Android@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"android 菜菜"<1925350623@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [tencentyun/SuperPlayer_Android] 能不能提供一个在列表中点击播放滑出暂停例子，方便集成！ (#73) 
 
 
 
 
 
  那有没有对内存性能有影响，我看那个封装的playerview里面控件很多。  
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:&amp;amp;nbsp;"卜鸣扬"<notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年3月26日(星期四) 中午12:37  
  收件人:&amp;amp;nbsp;"tencentyun/SuperPlayer_Android"<SuperPlayer_Android@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"782771031"<782771031@qq.com&amp;amp;gt;;"Comment"<comment@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [tencentyun/SuperPlayer_Android] 能不能提供一个在列表中点击播放滑出暂停例子，方便集成！ (#73)  
   
   
   
   
   
   嗯 是的&amp;amp;amp;nbsp;   
     
   发件人：卜鸣扬   
   邮箱：1925350623@qq.com   
   联系方式：15201296725   
     
     
   &amp;amp;amp;nbsp;   
     
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:&amp;amp;amp;nbsp;"MoYu"<notifications@github.com&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2020年3月26日(星期四) 中午12:35   
   收件人:&amp;amp;amp;nbsp;"tencentyun/SuperPlayer_Android"<SuperPlayer_Android@noreply.github.com&amp;amp;amp;gt;;   
   抄送:&amp;amp;amp;nbsp;"android 菜菜"<1925350623@qq.com&amp;amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [tencentyun/SuperPlayer_Android] 能不能提供一个在列表中点击播放滑出暂停例子，方便集成！ (#73)   
     
     
     
     
     
    那你是在每个item上面都放置了 superplayerview？    
       
       
       
       
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------    
    发件人:&amp;amp;amp;amp;nbsp;"卜鸣扬"<notifications@github.com&amp;amp;amp;amp;gt;;    
    发送时间:&amp;amp;amp;amp;nbsp;2020年3月26日(星期四) 中午12:34    
    收件人:&amp;amp;amp;amp;nbsp;"tencentyun/SuperPlayer_Android"<SuperPlayer_Android@noreply.github.com&amp;amp;amp;amp;gt;;    
    抄送:&amp;amp;amp;amp;nbsp;"782771031"<782771031@qq.com&amp;amp;amp;amp;gt;;"Comment"<comment@noreply.github.com&amp;amp;amp;amp;gt;;    
    主题:&amp;amp;amp;amp;nbsp;Re: [tencentyun/SuperPlayer_Android] 能不能提供一个在列表中点击播放滑出暂停例子，方便集成！ (#73)    
       
       
       
       
       
     嗯 ，我采用的是 显示 隐藏&amp;amp;amp;amp;amp;nbsp;     
     &amp;amp;amp;amp;amp;nbsp;     
         
     发件人：卜鸣扬     
     邮箱：1925350623@qq.com     
     联系方式：15201296725     
         
         
     &amp;amp;amp;amp;amp;nbsp;     
         
         
         
         
     ------------------&amp;amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;amp;nbsp;------------------     
     发件人: "MoYu"<notifications@github.com&amp;amp;amp;amp;amp;gt;;      
     发送时间: 2020年3月26日(星期四) 中午11:04     
     收件人: "tencentyun/SuperPlayer_Android"<SuperPlayer_Android@noreply.github.com&amp;amp;amp;amp;amp;gt;;      
     抄送: "android 菜菜"<1925350623@qq.com&amp;amp;amp;amp;amp;gt;; "Author"<author@noreply.github.com&amp;amp;amp;amp;amp;gt;;      
     主题: Re: [tencentyun/SuperPlayer_Android] 能不能提供一个在列表中点击播放滑出暂停例子，方便集成！ (#73)     
         
         
         
         
         
           
     所以你目前的实现方案呢，我们目前没有使用这个超级播放器，自己封装的播放器和播放view，在需要播放的地方，放置一个空的view，每次播放，把播放器add进去，不在播放的时候，在remove掉。
