### ISSUE TITLE
如果activity里面只放一个SuperPlayerView，那么全屏操作ok，但是放到列表就不行了

### ISSUE THREAD

**Issue by MoYuFly** [tencentyun/SuperPlayer_Android#75]
如果activity里面只放一个SuperPlayerView，那么全屏操作ok，但是放到列表就不行了，只是在item位置进行了横屏 播放，而不是全屏。这里有什么说法吗》

**Comment by ChaiChai210** [comment]
这个需要你自己去控制的。要把所有的都remove掉，然后再添加上去。具体你参考下，com.github.dueeeke.dkplayer这个

**Comment by MoYuFly** [comment]
好的，非常感谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ChaiChai210"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月31日(星期二) 晚上10:04
收件人:&nbsp;"tencentyun/SuperPlayer_Android"<SuperPlayer_Android@noreply.github.com&gt;;
抄送:&nbsp;"782771031"<782771031@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [tencentyun/SuperPlayer_Android] 如果activity里面只放一个SuperPlayerView，那么全屏操作ok，但是放到列表就不行了 (#75)





 
这个需要你自己去控制的。要把所有的都remove掉，然后再添加上去。具体你参考下，com.github.dueeeke.dkplayer这个
