### ISSUE TITLE
运行的时候闪退，按文档来操作的

### ISSUE THREAD

**Issue by DTJiro** [tencentyun/SuperPlayer_Android#78]
这是ERROR部分
04-04 23:26:06.221 4916-4940/com.example.course A/libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0xb73b9958 in tid 4940 (DFM Handler Thr)
04-04 23:26:06.959 4916-4946/com.example.course E/Unknow: [TXCIOListener.cpp, Listen, 698]:listen failed|error:4|info:Interrupted system call
04-04 23:26:07.061 4038-4186/? E/InputDispatcher: channel 'a17e1e5 com.example.course/com.example.course.activity.VideoActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

**Comment by wzyzb** [comment]
是使用demo奔溃吗？有没有具体复现路径。自己的APP请参照demo去使用api

**Comment by wzyzb** [comment]
请提供下具体的堆栈

**Comment by whalehe** [comment]
您好，Fatal signal 11 (SIGSEGV), code 2, fault addr 0xb73b9958 in tid 4940 (DFM Handler Thr)，libc是Android系统库，应该是错误的操作引起的崩溃
