### ISSUE TITLE
超级播放器显示hls key获取失败

### ISSUE THREAD

**Issue by hiliving** [tencentyun/SuperPlayer_Android#80]
https://www.chifenghualvlvxingshe.com/20190806/dBMrWQbN/index.m3u8

**Comment by shaojava** [comment]
参考#79的方法 
我修改后的demo代码测试改地址没问题

**Comment by shaojava** [comment]
官方demo有问题

**Comment by shaojava** [comment]
看了几分钟没问题 就是网络慢卡
