### ISSUE TITLE
TXLivePlayer 录播 startRecord报错  

### ISSUE THREAD

**Issue by ColaMachine** [tencentyun/SuperPlayer_Android#82]
这块demo有点少 ，我自己尝试startRecord报错  
TXLivePlayer
 Process: com.awifi.smarthome, PID: 31755
                  java.lang.UnsatisfiedLinkError: No implementation found for long com.tencent.liteav.muxer.jni.TXSWMuxerJNI.init() (tried Java_com_tencent_liteav_muxer_jni_TXSWMuxerJNI_init and Java_com_tencent_liteav_muxer_jni_TXSWMuxerJNI_init__)

**Comment by wzyzb** [comment]
看下so是否都拷贝到相应的目录下面了

**Comment by whalehe** [comment]
java.lang.UnsatisfiedLinkError，链接库错误，建议集成我们的AAR版SDK
```
compile 'com.tencent.liteav:LiteAVSDK_Player:latest.release'
```
