### ISSUE TITLE
怎么获得暂停的回调呢

### ISSUE THREAD

**Issue by lpc904586134** [tencentyun/SuperPlayer_Android#83]
文档中没有暂停的回调，怎么知道用户点击了暂停呢，难道要完全自定义

**Comment by lpc904586134** [comment]
我指的是SuperPlayerView这个

**Comment by whalehe** [comment]
您好，播放器主要通过状态机来控制，可以调SuperPlayerView.getPlayState，如果是SuperPlayerConst.PLAYSTATE_PAUSE，表示是暂停状态。
