### ISSUE TITLE
播放器的返回键可以动态设置显示隐藏吗？

### ISSUE THREAD

**Issue by shangxinlu034** [tencentyun/SuperPlayer_Android#86]
非全屏的情况下想隐藏掉返回键，请问有相关设置吗？

**Comment by whalehe** [comment]
你好，方便截图描述下具体是哪个返回键么？

**Comment by shangxinlu034** [comment]
播放器上面的返回键，全屏时点击返回小屏，小屏时再点击返回键会出现多出状态栏的情况，所以想问可不可以直接把他隐藏掉，用我自己的顶部返回键做返回操作

**Comment by whalehe** [comment]
您好，UI层的返回键，可以自己通过控制隐藏的
