### ISSUE TITLE
在Activity的onDestroy（）方法中释放资源，但是有时候app因为处于后台，activity被回收，没有走到这个生命周期，导致资源不能被释放，有什么好的解决方法吗

### ISSUE THREAD

**Issue by zzzsssbo** [tencentyun/SuperPlayer_Android#87]
在Activity的onDestroy（）方法中释放资源，但是有时候app因为处于后台，activity被回收，没有走到这个生命周期，导致资源不能被释放，有什么好的解决方法吗

**Comment by whalehe** [comment]
在退后台时，会执行onPause，可以在Activity中的onPause方法里处理
