### ISSUE TITLE
怎么关闭初始化最大亮度

### ISSUE THREAD

**Issue by huluxia** [tencentyun/SuperPlayer_Android#9]
如题，在手势调节那个utils设置根本没用，还会自己调整到最大亮度

 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by zhoutianling** [comment]
同问？

**Comment by AlphaHans** [comment]
TCVodMoreView 中这行代码注释
![image](https://user-images.githubusercontent.com/16743494/59671150-c16f0300-91ef-11e9-8bed-ae6377ac52fa.png)

**Comment by dengqicheng** [comment]
VideoGestureUtil，进入之后在加载TCVodMoreView时会默认将亮度设置到最大

**Comment by HancockY** [comment]
解决了
