### ISSUE TITLE
Demo里没有列表播放？

### ISSUE THREAD

**Issue by LuoYang2412** [tencentyun/SuperPlayer_Android#91]
+ 列表播放
 ![list](https://main.qcloudimg.com/raw/3ece479b33cdc7a458483d3eb1e78b1b.gif) ![fu](https://main.qcloudimg.com/raw/3af5501454ca107882b618dbb2c0d8ef.gif)

**Comment by zhengpengzheng** [comment]
同问

**Comment by whalehe** [comment]
您好，目前有改版，点击【超级播放器】，进入后，就有直播列表，点播列表，进行列表播放。gif图我们更新下
