### ISSUE TITLE
点播播放器TXVodPlayer 播放mp4格式的视频一开始会黑一下

### ISSUE THREAD

**Issue by dutay** [tencentyun/SuperPlayer_Android#95]
点播播放器TXVodPlayer 播放mp4格式的视频一开始会黑一下然后开始播放
问题机型 OppoR11s

**Comment by whalehe** [comment]
您好，业务层可以加loading圈，在第一帧出现时，再把loading圈隐藏。部分mp4的moov box在后面，解码播放时，需要拿到播放信息，才能播放。可以更新下我们最新版本7.4，如果还有问题，烦请附上日志或者截图信息。
