### ISSUE TITLE
为什么一进来亮度最高,这个要怎么调?

### ISSUE THREAD

**Issue by lvkaixuan** [tencentyun/SuperPlayer_Android#96]

**Comment by whalehe** [comment]
您好，可以/Demo/superplayerkit/src/main/java/com/tencent/liteav/demo/play/utils/TCVideoGestureUtil.java中把mBrightness的默认值1，改成0.5或者适合您的亮度值

**Comment by TomorrowLsn** [comment]
> 您好，可以/Demo/superplayerkit/src/main/java/com/tencent/liteav/demo/play/utils/TCVideoGestureUtil.java中把mBrightness的值设置为1，改成0.5或者适合您的亮度值

请问我是用gradle引入的，怎么调整初始亮度？
