### ISSUE TITLE
和im sdk有重复

### ISSUE THREAD

**Issue by sunyiyan** [tencentyun/SuperPlayer_Android#97]
im player用的都是腾讯的
LiteAVSDK_Player.aar ,LiteAVSDK_TRTC-7.3.9133.aar 有重复文件。
有LiteAVSDK.aar可以下载吗

**Comment by whalehe** [comment]
你好，可以使用我们的专业版，https://cloud.tencent.com/document/product/647/32689#.E4.B8.93.E4.B8.9A.E7.89.88.EF.BC.88professional.EF.BC.89
